# Basic Information 
title: Shuo Wei
position: Graduate Student
position_link: https://www.wgh-comb.net/members.html
affiliation: School of Mathematics, Shandong University
affiliation_link: https://www.math.sdu.edu.cn/
email: shuowei@mail.sdu.edu.cn

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: Shuo Wei, Shandong University, graph theory, extremal graph theory, digraph theory, Hamilton cycles
description: Shuo Wei is a graduate student at the School of Mathematics, Shandong University, working on extremal graph theory and digraph theory.
canonical: https://shuowei30.github.io/ShuoWei_SDU.github.io/

# Links 
# If you don't need one of them, you may delete the corresponding line.
cv_link: assets/files/curriculum_vitae.pdf
github_link: https://github.com/shuowei30

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/avatar.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
# Set this to false to hide the footer credit.
enable_footnote: true

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: true

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
